name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7  # Sesuaikan versi MySQL sesuai kebutuhan
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: aya_design
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    # Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, exif, pcntl, bcmath
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: none

    # Install Composer dependencies
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    # Copy .env.example to .env
    - name: Copy .env file
      run: cp .env.example .env

    # Generate application key
    - name: Generate app key
      run: php artisan key:generate

    # Wait for MySQL to be ready
    - name: Wait for MySQL to be ready
      run: sleep 10

    # Run database migrations using the local MySQL service
    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: aya_design
        DB_USERNAME: root
        DB_PASSWORD: ""
      run: php artisan migrate --force

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 6: Build and push Docker image to Docker Hub
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/aya_design_jihan_rawr:latest

    # Step 7: Deploy the Docker container without MySQL
    - name: Deploy Docker container
      run: |
        docker run -d -p 80:80 \
          --name laravel_app \
          --env DB_CONNECTION=mysql \
          --env DB_HOST=${{ secrets.DB_HOST }} \
          --env DB_PORT=${{ secrets.DB_PORT }} \
          --env DB_DATABASE=${{ secrets.DB_DATABASE }} \
          --env DB_USERNAME=${{ secrets.DB_USERNAME }} \
          --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          ${{ secrets.DOCKERHUB_USERNAME }}/aya_design_jihan_rawr:latest
